version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: classroom_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-classroom_api}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-classroom_api}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - classroom_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    labels:
      com.classroom.description: "PostgreSQL Database for Classroom API"
      com.classroom.service: "database"

  memcached:
    image: memcached:1.6-alpine
    container_name: classroom_memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    command: memcached -m 128
    networks:
      - classroom_network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    labels:
      com.classroom.description: "Memcached for Classroom API"
      com.classroom.service: "cache"

networks:
  classroom_network:
    driver: bridge
    name: classroom_network

volumes:
  postgres_data:
    name: classroom_postgres_data
